name: Live Server
on:
  push:
    branches:
      - main
jobs:
 build:
    name: Deploy Latest Code
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: Deploy Code to Prod Env.
      uses: appleboy/ssh-action@master
      with:
      #ssh:
        host: 18.134.220.86
        username: ubuntu
        password: Harpreet@123#
        timeout: 3s
        script: |
         cd /var/www/html/ims
         git stash
         git pull origin main
         git stash apply
         composer update
         sudo chmod -R 777 public/ app/ resources/ storage/
